- name: Setup MongoDB
  run: |
    docker pull mongo
    docker run -d --name mongo-dbserver -p 27017:27017 mongo
    sleep 15

- name: Test MongoDB
  run: |
    docker exec mongo-dbserver mongosh \
      --eval "db.runCommand({ ping: 1 })"

- name: Build with Maven
  run: mvn clean package

- name: Check target
  run: ls -la target

- name: Build Docker image
  run: docker build -t se_methods .

- name: Run Java container
  run: |
    docker run \
      --network container:mongo-dbserver \
      --name devopscontainer \
      se_methods

- name: View logs
  if: always()
  run: |
    docker ps -a
    docker logs devopscontainer 2>&1 || true
